version: "3.9"

services:
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        env_file:
            - .env.prod
    backend:
        image: 285785138545.dkr.ecr.ap-southeast-1.amazonaws.com/shopee-clone:latest
        command: "sh -c ./entrypoint.prod.sh"
        env_file:
            - .env.prod
        volumes:
            - ./backend:/backend
        ports:
            - 8000:8000
        depends_on: 
            - db
        links:
            - db:db
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - backend
    