version: "3.9"

services:
    db:
        env_file:
            - .env.prod
    backend:
        image: 285785138545.dkr.ecr.ap-southeast-1.amazonaws.com/shopee-clone:latest
        command: "sh -c ./entrypoint.prod.sh"
        env_file:
            - .env.prod
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - backend
