version: "3.9"

services:
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        env_file:
            - .env.dev
    backend:
        build: ./backend
        env_file:
            - .env.dev
        volumes:
            - ./backend:/backend
        ports:
            - "8000:8000"
        depends_on: 
            - db
        links:
            - db:db
    frontend:
        build: ./frontend
        volumes: 
            - ./frontend/:/frontend/
        ports:
            - "3000:3000"
        

